### ISSUE TITLE
[Bug] Non-ASCII symbols not converted

### ISSUE THREAD

**Issue by Kristinita** [jdc0589/CaseConversion#31]
### 1. Summary

Non-ASCII symbols not converted for me.

### 2. Expected behavior

![Case Conversion](http://i.imgur.com/MUlYl8R.gif)

1. Native Sublime Text Convert Case — Upper Case, Lower Case and so on — successfully work for me in Non-ASCII symbols.
2. Case Conversion worked for me for Latin letters.

### 3. Actual behavior

Case Conversion features don't worked for me for Cyrillic letters. I get stack trace.

```python
command: convert_to_camel
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "case_conversion in D:\Sublime Text 3 x64\Data\Installed Packages\Case Conversion.sublime-package", line 104, in run
  File "case_conversion in D:\Sublime Text 3 x64\Data\Installed Packages\Case Conversion.sublime-package", line 87, in run_on_selections
  File "case_conversion in D:\Sublime Text 3 x64\Data\Installed Packages\Case Conversion.sublime-package", line 31, in to_camel_case
IndexError: list index out of range
```

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I nave any Cyrillic text, for example,

    Кристина Беспрецедентна

I select text → <kbd>Ctrl+Shift+P</kbd> → `ConvertCase: camelCase` → I get actual behavior.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by dlnsk** [comment]
OS: Linux

Convert Cyrillic to snake_case change selection to nothing.
https://stackoverflow.com/questions/36187349/python-regex-for-unicode-capitalized-words
